// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjYy0LBgEhDss0FdsSoHoJSWd475bbzls',
    appId: '1:580962129559:android:b1e5177df3e4b12841bbd2',
    messagingSenderId: '580962129559',
    projectId: 'todoapp-7a0ba',
    storageBucket: 'todoapp-7a0ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvbuOvoNTTwe7Ld4ntLoW6V5jFGj7KHc4',
    appId: '1:580962129559:ios:87424b191a30d97a41bbd2',
    messagingSenderId: '580962129559',
    projectId: 'todoapp-7a0ba',
    storageBucket: 'todoapp-7a0ba.appspot.com',
    iosBundleId: 'com.santiagocastaneda.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvbuOvoNTTwe7Ld4ntLoW6V5jFGj7KHc4',
    appId: '1:580962129559:ios:b30382144588355b41bbd2',
    messagingSenderId: '580962129559',
    projectId: 'todoapp-7a0ba',
    storageBucket: 'todoapp-7a0ba.appspot.com',
    iosBundleId: 'com.santiagocastaneda.todoApp.RunnerTests',
  );
}
